### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by hkystar35**
`New-ClientDevice`
Adding check to create HGS Guardian if not present
added erroraction on `Get-HGSGuardian` line
`Publish-AutoPilotConfig`
Create folder if needed and dismount VHDX

### CODE REVIEW

**Comment by tabs-not-spaces** [comment]
@hkystar35 which issues does this close?

**Comment by hkystar35** [comment]
Should close all 3 that I submitted. I'm not sure how, or if, issues can be linked to Pull Requests, sorry.

**Comment by hkystar35** [comment]
Should close #(4,5,6)

**Comment by tabs-not-spaces** [comment]
awesome - happy to merge

**Pull request merged**
